# Header
menu:
  主页: /
  所有文章: /archives
  微信订阅: /weichat

# SubNav
subnav:
  github: "https://github.com/lslvxy"
  weibo: "http://weibo.com/lslvxy"
  rss: "atom.xml"
  # zhihu: "http://zhihu.com/people/lslvxy"
  #douban: "#"
  mail: "mailto:lslvxy@163.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

sitemap:
    path: sitemap.xml


# Content
excerpt_link: more
fancybox: false
mathjax: false

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: 'UA-46012981-1'
cnzz_protocol: true
favicon: /favicon.png

#你的头像url
avatar: http://lise-blog.oss-cn-shanghai.aliyuncs.com/fb.jpg
#是否开启分享
share_jia: true
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: lise
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  博客园地址: http://cnblogs.com/lslvxy
  刘江华的博客: http://www.yanyaner.com/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 朴实，简单，清淡无华，平凡中显珍贵，平淡中见真情。
