language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cp ./source/_redirects ./public/
  - cd ./public
  - git init
  - git config user.name "lise"
  - git config user.email "lslvxy@gmail.com"
  - git add .
  - git commit -m "travis-ci build"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/lslvxy/lslvxy.github.com.git